# -*- coding: utf-8 -*-
"""cem_ilhan_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ws0eFWYwe3t6uMgVnUwSfhaO3oyVEjwN

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""

Ercan Cem İlhan

1506631

"""Describe what an algorithm is."""

An algorithm is a designed way to solve a specific problem or to achieve a conclusion.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

The brute force method is solving a specific problem by checking all the possible cases which is a very slow process. But an algorithmic design, like the Binary Search Tree method, works more efficiently as it cuts the searching process by half every checks.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

I think, an algorithmic design approach can help me work more efficiently through my design thinking process. During the process of searching for new concepts and ideas, what we actually do as designers is eliminate the other ideas, try to prove ourselves wrong, try to find the reasoning behind “Why it wouldn’t work?” so if I get more and more used to doing algorithmic thinking as I am trying to come up with new ideas, this algorithmic way of solving problems can be very efficient and helpful for me.

"""Create a python dictionary for your name surname and year of birth."""

dict_cem = {'name':'cem','surname':'ilhan','age':'21'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if 'name'[0] == 'a':
  print('True! Your initial is a')
else:
  print('False! Your initial is a different letter.')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len('ilhan')%3 == 1: 
   print('It is divisible.')
else:
   print('Not divisible.')

"""Change your year of birth to 2678."""

dict_cem['age'] = '2678'

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""